#!/usr/bin/env python3
"""Generate _includes/head-custom.html (schema.org JSON-LD) from projects.json.

The primer theme includes head-custom.html inside <head> on every page.
The home page gets the whole collection; each project page gets its own entry.

Usage:
  python3 scripts/build_jsonld.py          # write the include
  python3 scripts/build_jsonld.py --check  # exit 1 if the include is out of date
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "projects.json"
TARGET = ROOT / "_includes" / "head-custom.html"

SITE_URL = "https://merihilgor.github.io/open-projects/"
LICENSE_URL = "https://creativecommons.org/licenses/by-nc-sa/4.0/"


def person(author):
    return {"@type": "Person", "name": author["name"], "url": "https://github.com/merihilgor"}


def project_node(p, author, languages):
    return {
        "@type": "CreativeWork",
        "@id": f"{SITE_URL}{p['slug']}/",
        "url": f"{SITE_URL}{p['slug']}/",
        "name": p["title"],
        "alternateName": p["title_tr"],
        "description": p["summary"],
        "about": p["theme"],
        "genre": p["type"],
        "keywords": ", ".join(p["keywords"] + p.get("keywords_tr", [])),
        "inLanguage": languages,
        "license": LICENSE_URL,
        "isAccessibleForFree": True,
        "author": person(author),
        "sameAs": p["url"],
    }


def script_tag(data):
    body = json.dumps(data, ensure_ascii=False, indent=2)
    # Keep "</" out of the script body so it can never close the tag early.
    body = body.replace("</", "<\\/")
    return f'<script type="application/ld+json">\n{body}\n</script>'


def render():
    d = json.loads(SOURCE.read_text(encoding="utf-8"))
    author, languages = d["author"], d["languages"]
    projects = [project_node(p, author, languages) for p in d["projects"]]

    collection = {
        "@context": "https://schema.org",
        "@type": "Collection",
        "@id": SITE_URL,
        "url": SITE_URL,
        "name": d["name"],
        "description": d["description"],
        "inLanguage": languages,
        "license": LICENSE_URL,
        "isAccessibleForFree": True,
        "author": person(author),
        "sameAs": d["url"],
        "hasPart": projects,
    }

    out = [
        "<!-- Generated by scripts/build_jsonld.py from projects.json. Do not edit by hand. -->",
        '{% if page.url == "/" %}',
        script_tag(collection),
    ]
    for node in projects:
        slug = node["url"][len(SITE_URL):]
        out.append(f'{{% elsif page.dir == "/{slug}" %}}')
        out.append(script_tag({"@context": "https://schema.org", **node,
                               "isPartOf": {"@id": SITE_URL}}))
    out.append("{% endif %}")
    return "\n".join(out) + "\n"


def main():
    content = render()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            print(f"{TARGET.relative_to(ROOT)} is out of date; run scripts/build_jsonld.py")
            return 1
        print("JSON-LD include is up to date")
        return 0
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
